# Generated by Django 4.2.7 on 2025-08-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationlog',
            new_name='integration_service_38db09_idx',
            old_name='integration_service_fb7b1d_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationlog',
            new_name='integration_status_9ad1f1_idx',
            old_name='integration_status_7e2a61_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationlog',
            new_name='integration_task_id_432ae1_idx',
            old_name='integration_task_id_c6e456_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationlog',
            new_name='integration_project_feb9cb_idx',
            old_name='integration_project_3e9a44_idx',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='is_mock_mode',
        ),
    ]
