# Generated by Django 4.2.7 on 2025-08-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_add_is_mock_mode_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='is_mock_mode',
        ),
    ]
